"""
TRACE anthropogenic carbon functions for oae-tmm.

Provides two public functions:

  interp_trace — interpolates the TRACE gridded product (downloaded
      from https://zenodo.org/records/15003059) or a user-created
      TRACE gridded product (using calculate_canth) to the
      OCIM2-48L grid for a given time and emissions scenario. Uses a
      RegularGridInterpolator and fills remaining NaN cells with
      grid.inpaint_nans_3d.

  calculate_canth — uses the pyTRACE neural network to predict anthropogenic
      carbon from temperature and salinity at every ocean grid cell. A two-pass
      approach handles the case where pyTRACE returns negative preformed
      nutrients on the first pass.

Both functions return 3D arrays of shape (n_lat, n_lon, n_depth) on the
OCIM2-48L grid, NaN at land cells.

Note on the 'none' scenario
----------------------------
'none' is NOT the TRACE historical scenario. In the experiment framework,
'none' means atmospheric CO2 is frozen at the first time step (no future
emissions perturbation), as implemented in chemistry.get_co2_scenario.
For Canth initial conditions, however, both functions still need a Canth
estimate — they use pyTRACE/TRACE scenario 1, which is a linear
extrapolation of the historical trend from 2012–2022. This is separate
from the atmospheric CO2 forcing used during the simulation.
"""

import warnings

import numpy as np
import xarray as xr
from scipy.interpolate import RegularGridInterpolator
from pyTRACE import trace

from oae_tmm.grid import inpaint_nans_3d, make_3d


def interp_trace(data_path, time, scenario, lat, lon, depth, ocnmask):
    """Interpolate TRACE gridded Canth product to the OCIM2-48L grid.

    Opens the appropriate TRACE netCDF file for the given time and emissions
    scenario, interpolates in time, then regrids from the TRACE lat/lon/depth
    grid to the OCIM2-48L grid using a RegularGridInterpolator. NaN cells
    (land/bathymetry mismatches) are filled with inpaint_nans_3d.

    If time is before 2020, historical/none scenario is used. If time is
    after 2020, one of the following emissions scenarios must be specified:
    ssp119, ssp126, ssp245, ssp370, ssp370_lowNTCF, ssp434, ssp460, ssp534_OS	
    
    TRACE data source: https://zenodo.org/records/15003059.

    Parameters
    ----------
    data_path : str
        Path to the folder containing the TRACE_gridded/ subdirectory.
    time : float
        Time of interest [decimal years CE].
    scenario : str
        Emissions scenario. One of: 'none', 'ssp119', 'ssp126', 'ssp245',
        'ssp370', 'ssp370_lowNTCF', 'ssp434', 'ssp460', 'ssp534_OS'.
    lat : np.ndarray
        1D array of OCIM2-48L latitudes [°N].
    lon : np.ndarray
        1D array of OCIM2-48L longitudes [°E].
    depth : np.ndarray
        1D array of OCIM2-48L depth levels [m].
    ocnmask : np.ndarray
        Integer mask of shape (n_lat, n_lon, n_depth); 1 = ocean, 0 = land.

    Returns
    -------
    np.ndarray
        Anthropogenic carbon [µmol kg^-1], shape (n_lat, n_lon, n_depth),
        NaN at land cells.
    """
    scenarios = {
        'none': 1, 'ssp119': 2, 'ssp126': 3, 'ssp245': 4, 'ssp370': 5,
        'ssp370_lowNTCF': 6, 'ssp434': 7, 'ssp460': 8, 'ssp534_OS': 9,
    }

    if scenario not in scenarios:
        raise ValueError(
            f"Invalid scenario {scenario!r}. Must be one of: {', '.join(scenarios.keys())}"
        )

    if time > 2500:
        warnings.warn('TRACE data is only available to 2500. Interpolating past this point is not advised.')

    # Three file sources, chosen by time range:
    #
    #   2020–2100  OCIM_CanthFromTRACECO2Pathway{N}.nc
    #              High-resolution product on the OCIM2-48L grid, generated by
    #              scripts/make_trace_gridded.py at yearly intervals. Used for
    #              the main simulation window — fewer regridding artefacts
    #              compared to the published product.
    #
    #   >2100      CanthFromTRACECO2Pathway{N}.nc
    #              Original published TRACE gridded product (Fay et al.),
    #              sparse time axis (decadal to centennial), used as fallback
    #              for extended projections.
    #              Archived at https://zenodo.org/records/15692788.
    #
    #   <2020      CanthFromTRACECO2Pathway1.nc
    #              Historical file (scenario 1 = none/historical), since SSP
    #              scenarios have not yet diverged before 2020.

    if 2020 <= time <= 2100:
        if scenario == 'none' and time > 2022:
            warnings.warn("'none' scenario chosen, but time > 2022 selected. "
                          "Canth is based on a linear extrapolation from 2012-2022.")
        trace_data = xr.open_dataset(
            data_path + 'TRACE_gridded/OCIM_CanthFromTRACECO2Pathway' + str(scenarios[scenario]) + '.nc',
            decode_times=False,
        )
    elif time > 2100:
        if scenario == 'none':
            warnings.warn("'none' scenario chosen, but time > 2020 selected. "
                          "Canth is based on a linear extrapolation from 2012-2022.")
        trace_data = xr.open_dataset(
            data_path + 'TRACE_gridded/CanthFromTRACECO2Pathway' + str(scenarios[scenario]) + '.nc',
            decode_times=False,
        )
    else:
        trace_data = xr.open_dataset(
            data_path + 'TRACE_gridded/CanthFromTRACECO2Pathway1.nc',
            decode_times=False,
        )

    trace_data = trace_data.interp(time=time)

    trace_lat = trace_data['lat'].to_numpy()     # ºN
    trace_lon = trace_data['lon'].to_numpy()     # ºE
    trace_depth = trace_data['depth'].to_numpy() # m below sea surface

    canth = trace_data['canth'].transpose('lat', 'lon', 'depth').copy().values

    interp = RegularGridInterpolator(
        (trace_lat, trace_lon, trace_depth), canth, bounds_error=False, fill_value=None,
    )

    # TRACE longitude runs 20°E–380°E; temporarily shift OCIM longitudes < 20°E to match
    lon[lon < 20] += 360

    lat_grid, lon_grid, depth_grid = np.meshgrid(lat, lon, depth, indexing='ij')
    query_points = np.column_stack([lat_grid.ravel(), lon_grid.ravel(), depth_grid.ravel()])

    canth = interp(query_points).reshape(lat_grid.shape)
    canth = inpaint_nans_3d(canth, mask=ocnmask)

    # shift longitudes back
    lon[lon > 360] -= 360

    return canth


def calculate_canth(scenario, year, T_3D, S_3D, ocnmask, lat, lon, depth):
    """Predict anthropogenic carbon using TRACE.

    Runs TRACE at every ocean grid cell using temperature and salinity as
    predictors. A two-pass approach is used: the first pass recovers preformed
    nutrient and alkalinity values; the second pass clamps any negative values
    to zero (a known TRACE artefact) and reruns to produce clean Canth
    estimates.

    Parameters
    ----------
    scenario : str
        Emissions scenario. One of: 'none', 'ssp119', 'ssp126', 'ssp245',
        'ssp370', 'ssp370_lowNTCF', 'ssp434', 'ssp460', 'ssp534_OS', 'REMIND'.
        'none' maps to pyTRACE scenario 1 (historical linear extrapolation
        from 2012–2022) for Canth estimation only — it does NOT mean the
        atmospheric CO2 is frozen here. Freezing CO2 is handled separately
        by chemistry.get_co2_scenario at experiment time.
    year : float
        Year to evaluate anthropogenic carbon at [decimal years CE].
    T_3D : np.ndarray
        Temperature [°C], shape (n_lat, n_lon, n_depth).
    S_3D : np.ndarray
        Salinity [unitless], shape (n_lat, n_lon, n_depth).
    ocnmask : np.ndarray
        Integer mask of shape (n_lat, n_lon, n_depth); 1 = ocean, 0 = land.
    lat : np.ndarray
        1D array of OCIM2-48L latitudes [°N].
    lon : np.ndarray
        1D array of OCIM2-48L longitudes [°E].
    depth : np.ndarray
        1D array of OCIM2-48L depth levels [m].

    Returns
    -------
    np.ndarray
        Anthropogenic carbon [µmol kg^-1], shape (n_lat, n_lon, n_depth),
        NaN at land cells.
    """
    if year > 2022 and scenario == 'none':
        warnings.warn("'none' scenario chosen, but year > 2022 selected. "
                      "Canth is based on a linear extrapolation from 2012-2022.")

    scenario_dict = {
        'none': 1, 'ssp119': 2, 'ssp126': 3, 'ssp245': 4, 'ssp370': 5,
        'ssp370_lowNTCF': 6, 'ssp434': 7, 'ssp460': 8, 'ssp534_OS': 9, 'REMIND': 10,
    }

    # pyTRACE expects (lon, lat, depth) ordering — transpose from OCIM (lat, lon, depth)
    T_3D_T = T_3D.transpose([1, 0, 2])
    S_3D_T = S_3D.transpose([1, 0, 2])
    ocnmask_T = ocnmask.transpose([1, 0, 2])

    predictor_measurements = np.vstack([
        S_3D_T.flatten(order='F'), T_3D_T.flatten(order='F'),
    ]).T
    predictor_measurements = predictor_measurements[ocnmask_T.flatten(order='F').astype(bool)]

    lon_grid, lat_grid, depth_grid = np.meshgrid(lon, lat, depth, indexing='ij')
    ocim_coordinates = np.column_stack([
        lon_grid.ravel(order='F'),
        lat_grid.ravel(order='F'),
        depth_grid.ravel(order='F'),
    ])
    ocim_coordinates = ocim_coordinates[ocnmask_T.flatten(order='F').astype(bool)]

    dates = year * np.ones(ocim_coordinates.shape[0])

    # first pass: retrieve preformed values (pyTRACE sometimes returns these as < 0)
    trace_output = trace(
        output_coordinates=ocim_coordinates,
        dates=dates,
        predictor_measurements=predictor_measurements,
        predictor_types=[1, 2],
        atm_co2_trajectory=scenario_dict[scenario],
        verbose_tf=False,
    )

    preformed_p = trace_output.preformed_p.values
    preformed_p[preformed_p < 0] = 0
    preformed_ta = trace_output.preformed_ta.values
    preformed_si = trace_output.preformed_si.values
    preformed_si[preformed_si < 0] = 0
    scale_factors = trace_output.scale_factors.values

    # second pass: rerun with clamped preformed values to get clean Canth
    trace_output = trace(
        output_coordinates=ocim_coordinates,
        dates=dates,
        predictor_measurements=predictor_measurements,
        predictor_types=[1, 2],
        atm_co2_trajectory=scenario_dict[scenario],
        preformed_p=preformed_p,
        preformed_ta=preformed_ta,
        preformed_si=preformed_si,
        scale_factors=scale_factors,
        verbose_tf=False,
    )

    # expand back to (lon, lat, depth), then transpose to OCIM (lat, lon, depth)
    canth_3D = make_3d(trace_output.canth.values, ocnmask_T).transpose([1, 0, 2])

    return canth_3D
