"""
TRACE anthropogenic carbon functions for oae-tmm.

Provides two public functions:

  interp_trace — interpolates the TRACE gridded product (downloaded
      from https://zenodo.org/records/15003059) or a user-created
      TRACE gridded product (using calculate_canth) to the
      OCIM2-48L grid for a given time and emissions scenario. Uses a
      RegularGridInterpolator and fills remaining NaN cells with
      grid.inpaint_nans_3d.

  calculate_canth — uses the pyTRACE neural network to predict anthropogenic
      carbon from temperature and salinity at every ocean grid cell. A two-pass
      approach handles the case where pyTRACE returns negative preformed
      nutrients on the first pass.

Both functions return 3D arrays of shape (n_lat, n_lon, n_depth) on the
OCIM2-48L grid, NaN at land cells.

Note on the 'none' scenario
----------------------------
'none' is NOT the TRACE historical scenario. In the experiment framework,
'none' means Canth is held fixed at the start year (no future Canth update
in the time loop). Both functions still need a Canth estimate — they use
pyTRACE/TRACE scenario 1, which is a linear extrapolation of the historical
trend from 2012–2022 for years beyond 2022.

Reference: Carter, B. R. et al. (2025). Tracer-based Rapid Anthropogenic
Carbon Estimation (TRACE). Earth System Science Data, 17(6), 3073-3088.
https://doi.org/10.5194/essd-17-3073-2025.
"""

import functools
import warnings

import numpy as np
import xarray as xr
from scipy.interpolate import RegularGridInterpolator
from pyTRACE import trace

from oae_tmm.grid import inpaint_nans_3d, make_3d


@functools.lru_cache(maxsize=None)
def _load_trace_dataset(filepath: str) -> xr.Dataset:
    return xr.open_dataset(filepath, decode_times=False)


def interp_trace(data_path, time, scenario, latitude, longitude, depth, ocnmask):
    """Interpolate TRACE gridded Canth product to the OCIM2-48L grid.

    Opens the appropriate TRACE netCDF file for the given time and emissions
    scenario, interpolates in time, then regrids from the TRACE lat/lon/depth
    grid to the OCIM2-48L grid using a RegularGridInterpolator. NaN cells
    (land/bathymetry mismatches) are filled with inpaint_nans_3d.

    Historical/linear scenario relies on historical data (Mauna Loa) through
    2022, and a linear extrapolation based on the average trend from 2012-2022
    is used to estimate Canth after 2022. It is not recommended to use this
    scenario for future projections.
    
    If time is after 2022, one of the following emissions scenarios should be
    specified: ssp119, ssp126, ssp245, ssp370, ssp370_lowNTCF, ssp434, ssp460,
    ssp534_OS. These scenarios diverge from the historical/linear scenario
    beginning in 1960 and from each other in 2017. See Meinshausen et al.
    (2020) for details.

    A higher resolution (yearly) TRACE gridded product has been created for the
    years 2022-2100 to minimize interpolation during time periods of high
    interest. See scripts/make_trace_gridded.py.

    TRACE data source: https://zenodo.org/records/15003059.

    Parameters
    ----------
    data_path : str
        Path to the folder containing the TRACE_gridded/ subdirectory.
    time : float
        Time of interest [decimal years CE].
    scenario : str
        Emissions scenario. One of: 'none', 'ssp119', 'ssp126', 'ssp245',
        'ssp370', 'ssp370_lowNTCF', 'ssp434', 'ssp460', 'ssp534_OS'.
    latitude : np.ndarray
        1D array of OCIM2-48L latitudes [°N].
    longitude : np.ndarray
        1D array of OCIM2-48L longitudes [°E].
    depth : np.ndarray
        1D array of OCIM2-48L depth levels [m].
    ocnmask : np.ndarray
        Integer mask of shape (n_lat, n_lon, n_depth); 1 = ocean, 0 = land.

    Returns
    -------
    np.ndarray
        Anthropogenic carbon [µmol kg^-1], shape (n_lat, n_lon, n_depth),
        NaN at land cells.
    """
    scenarios = {
        'none': 1, 'ssp119': 2, 'ssp126': 3, 'ssp245': 4, 'ssp370': 5,
        'ssp370_lowNTCF': 6, 'ssp434': 7, 'ssp460': 8, 'ssp534_OS': 9,
    }

    if scenario not in scenarios:
        raise ValueError(
            f"Invalid scenario {scenario!r}. Must be one of: {', '.join(scenarios.keys())}"
        )

    if time > 2500:
        warnings.warn('TRACE data is only available to 2500. Interpolating past this point is not advised.')

    # Three file sources, chosen by time range:
    #
    #   2022–2100  OCIM_CanthFromTRACECO2Pathway{N}.nc
    #              High-resolution product on the OCIM2-48L grid, generated by
    #              scripts/make_trace_gridded.py at yearly intervals. Used for
    #              the main simulation window — fewer interpolation issues
    #              compared to the published product.
    #
    #   >2100      CanthFromTRACECO2Pathway{N}.nc
    #              Original published TRACE gridded product (Carter et al.),
    #              sparse time axis (decadal to centennial), used as fallback
    #              for extended projections.
    #
    #   >2022      CanthFromTRACECO2Pathway1.nc
    #              Original published TRACE gridded product (Carter et al.),
    #              which contains historical/linear scenario. This product
    #              is used for historical data.

    if 2022 <= time <= 2100:
        if scenario == 'none' and time > 2022:
            warnings.warn("'none' scenario chosen, but time > 2022 selected. "
                          "Canth is based on a linear extrapolation from 2012-2022.")
        filepath = data_path + 'TRACE_gridded/OCIM_CanthFromTRACECO2Pathway' + str(scenarios[scenario]) + '.nc'
    elif time > 2100:
        if scenario == 'none' and time > 2022:
            warnings.warn("'none' scenario chosen, but time > 2022 selected. "
                          "Canth is based on a linear extrapolation from 2012-2022.")
        filepath = data_path + 'TRACE_gridded/CanthFromTRACECO2Pathway' + str(scenarios[scenario]) + '.nc'
    else:
        filepath = data_path + 'TRACE_gridded/CanthFromTRACECO2Pathway1.nc'

    trace_data = _load_trace_dataset(filepath).interp(time=time)

    trace_lat = trace_data['lat'].to_numpy()     # ºN
    trace_lon = trace_data['lon'].to_numpy()     # ºE
    trace_depth = trace_data['depth'].to_numpy() # m below sea surface

    canth = trace_data['canth'].transpose('lat', 'lon', 'depth').copy().values

    interp = RegularGridInterpolator(
        (trace_lat, trace_lon, trace_depth), canth, bounds_error=False, fill_value=None,  # type: ignore[arg-type]
    )

    # TRACE longitude runs 20°E–380°E; shift a local copy of OCIM longitudes < 20°E to match
    lon_shifted = longitude.copy()
    lon_shifted[lon_shifted < 20] += 360

    lat_grid, lon_grid, depth_grid = np.meshgrid(latitude, lon_shifted, depth, indexing='ij')
    query_points = np.column_stack([lat_grid.ravel(), lon_grid.ravel(), depth_grid.ravel()])

    canth = interp(query_points).reshape(lat_grid.shape)
    canth = inpaint_nans_3d(canth, mask=ocnmask)

    return canth


def calculate_canth(scenario, year, temperature_3d, salinity_3d, ocnmask, latitude, longitude, depth):
    """Predict anthropogenic carbon using TRACE.

    Runs TRACE at every ocean grid cell using temperature and salinity as
    predictors. A two-pass approach is used: the first pass recovers preformed
    nutrient and alkalinity values; the second pass clamps any negative values
    to zero (a known TRACE artefact) and reruns to produce clean Canth
    estimates.

    Parameters
    ----------
    scenario : str
        Emissions scenario. One of: 'none', 'ssp119', 'ssp126', 'ssp245',
        'ssp370', 'ssp370_lowNTCF', 'ssp434', 'ssp460', 'ssp534_OS', 'REMIND'.
        'none' maps to pyTRACE scenario 1 (historical linear extrapolation
        from 2012–2022) for Canth estimation only — it does NOT mean the
        atmospheric CO2 is frozen here. Freezing CO2 is handled separately
        in the time loop (scenario != 'none' check in BaseExperiment.run).
    year : float
        Year to evaluate anthropogenic carbon at [decimal years CE].
    temperature_3d : np.ndarray
        Temperature [°C], shape (n_lat, n_lon, n_depth).
    salinity_3d : np.ndarray
        Salinity [unitless], shape (n_lat, n_lon, n_depth).
    ocnmask : np.ndarray
        Integer mask of shape (n_lat, n_lon, n_depth); 1 = ocean, 0 = land.
    latitude : np.ndarray
        1D array of OCIM2-48L latitudes [°N].
    longitude : np.ndarray
        1D array of OCIM2-48L longitudes [°E].
    depth : np.ndarray
        1D array of OCIM2-48L depth levels [m].

    Returns
    -------
    np.ndarray
        Anthropogenic carbon [µmol kg^-1], shape (n_lat, n_lon, n_depth),
        NaN at land cells.
    """
    if year > 2022 and scenario == 'none':
        warnings.warn("'none' scenario chosen, but year > 2022 selected. "
                      "Canth is based on a linear extrapolation from 2012-2022.")

    scenario_dict = {
        'none': 1, 'ssp119': 2, 'ssp126': 3, 'ssp245': 4, 'ssp370': 5,
        'ssp370_lowNTCF': 6, 'ssp434': 7, 'ssp460': 8, 'ssp534_OS': 9, 'REMIND': 10,
    }

    # pyTRACE expects (lon, lat, depth) ordering — transpose from OCIM (lat, lon, depth)
    temperature_3d_T = temperature_3d.transpose([1, 0, 2])
    salinity_3d_T    = salinity_3d.transpose([1, 0, 2])
    ocnmask_T = ocnmask.transpose([1, 0, 2])

    predictor_measurements = np.vstack([
        salinity_3d_T.flatten(order='F'), temperature_3d_T.flatten(order='F'),
    ]).T
    predictor_measurements = predictor_measurements[ocnmask_T.flatten(order='F').astype(bool)]

    lon_grid, lat_grid, depth_grid = np.meshgrid(longitude, latitude, depth, indexing='ij')
    ocim_coordinates = np.column_stack([
        lon_grid.ravel(order='F'),
        lat_grid.ravel(order='F'),
        depth_grid.ravel(order='F'),
    ])
    ocim_coordinates = ocim_coordinates[ocnmask_T.flatten(order='F').astype(bool)]

    dates = year * np.ones(ocim_coordinates.shape[0])

    # first pass: retrieve preformed values (pyTRACE sometimes returns these as < 0)
    trace_output = trace(
        output_coordinates=ocim_coordinates,
        dates=dates,
        predictor_measurements=predictor_measurements,
        predictor_types=[1, 2],
        atm_co2_trajectory=scenario_dict[scenario],
        verbose_tf=False,
    )

    preformed_p = trace_output.preformed_p.values
    preformed_p[preformed_p < 0] = 0
    preformed_ta = trace_output.preformed_ta.values
    preformed_si = trace_output.preformed_si.values
    preformed_si[preformed_si < 0] = 0
    scale_factors = trace_output.scale_factors.values

    # second pass: rerun with clamped preformed values to get clean Canth
    trace_output = trace(
        output_coordinates=ocim_coordinates,
        dates=dates,
        predictor_measurements=predictor_measurements,
        predictor_types=[1, 2],
        atm_co2_trajectory=scenario_dict[scenario],
        preformed_p=preformed_p,
        preformed_ta=preformed_ta,
        preformed_si=preformed_si,
        scale_factors=scale_factors,
        verbose_tf=False,
    )

    # expand back to (lon, lat, depth), then transpose to OCIM (lat, lon, depth)
    canth_3d = make_3d(trace_output.canth.values, ocnmask_T).transpose([1, 0, 2])

    return canth_3d
